# Configure this Discovery Server
spring:
  application:
    name: @project.artifactId@

build:
  version: @project.version@
  timestamp: @maven.build.timestamp@

server:
  port: 8761   # HTTP (Tomcat) port -- default Eureka runs on port 8761

# Configure this Discovery Server

# eureka by default will register itself as a client. So, we need to set it to false.
# What's a client server? See other microservices (account, product, etc).
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false

# >- remember -< serviceUrl = service-url