# service name
spring:
  profiles:
    active: native
  application:
    name: @project.artifactId@
  cloud:
    config:
      server:
        native:
          searchLocations: @config-files-base-url@

build:
  version: @project.version@
  timestamp: @maven.build.timestamp@

server:
  port: 8888

# eureka server
eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}